services:
  - type: web
    name: fastapi-app
    env: python
    build_command: "pip install -r requirements.txt"
    start_command: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker app:app"
    health_check_path: "/"
    ports:
      - port: 10000
        protocol: tcp
    instance_class: "t2.medium" # Adjust based on your needs
